name: terraform-apply

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        default: 'poc'
        required: true



jobs:

  terraform-apply: 
    runs-on: ubuntu-latest

  #  defaults:
   #   run:
    #    working-directory: poc
      
    env:
      ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}

    steps:
      - uses: actions/checkout@master

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init 

      - name: Terraform Plan
        run: terraform plan --var-file="./${{ github.event.inputs.env }}/${{ github.event.inputs.env}}.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve --var-file="./${{ github.event.inputs.env }}/${{ github.event.inputs.env}}.tfvars"
